### ISSUE TITLE
NoMethodError: undefined method `body' for nil:NilClass

### ISSUE THREAD

**Issue by aarthiraj561** [transloadit/ruby-sdk#53] opened 2018-10-31 05:45 UTC
I am using transloadit gem version '1.0.4' on ruby ruby-1.9.3-p551.
I receive the error 

```
NoMethodError: undefined method `body' for nil:NilClass
from /Users/aarram/.rvm/gems/ruby-1.9.3-p551@srma_api/gems/transloadit-1.0.4/lib/transloadit/response.rb:34:in `body'
```

when I do

```ruby
require 'transloadit'

file_to_process = "https://dashboarddev.s3.amazonaws.com/e1/840430299911e786fee949b8f945fb/Penguins.png"

transloadit = Transloadit.new(
:key => KEY,
:secret => SECRET_KEY)

import = transloadit.step 'import', '/http/import',
{ :url => file_to_process}

resize_avatar = transloadit.step 'resize_avatar', '/image/resize',
{ :use => "import",
:background => "transparent",
:resize_strategy => "pad",
:width => 50,
:height => 50,
:format => "png" }

export = transloadit.step 'export', '/sftp/store',
{ :use => "resize_avatar",
:user => "sshacs",
:host => HOST,
:path => PATH,
:url_template => URL_TEMPLATE,
:ssl_url_template => SSL_URL_TEMPLATE,
:sshkey => SSH_KEY }

assembly = transloadit.assembly(
:steps => [ import, resize_avatar, export ]
)

response = assembly.submit!
```

Can you please help me? Currently I do not want to upgrade my ruby version.

**Comment by aarthiraj561** [comment] 2018-10-31 07:48
Thanks for your suggestion @rmehner. I tried using transloadit version 1.2.0 and still see same issue.

Gemfile:
gem 'transloadit', '1.2.0'

Gemfile.lock
transloadit (1.2.0)
      mime-types (~> 2.99)
      multi_json
      rest-client

Request(with the same above described)
response = assembly.submit!

result:
NoMethodError: undefined method `body' for nil:NilClass
from /Users/aarram/.rvm/gems/ruby-1.9.3-p551@srma_api/gems/transloadit-1.2.0/lib/transloadit/response.rb:34:in `body'

Please let me know your suggestions.

**Comment by mfilej** [comment] 2019-04-04 10:52
We're seeing the same error pop up from time to time in our exception tracker. Due to the volume of uploads we can't identify which assembly belongs to the exception. Additionally, looking at assemblies from the day when the exception happened, it seems they were all completed successfully.

Is there any chance that the gem could catch this error and show more details, such as the associated assembly ID?

**Comment by cspeer** [comment] 2020-10-27 22:33
We just encountered the same problem and just like @mfilej we cannot find an assembly that appears to be responsible.

We are running
Ruby 2.7.2
Rails 6.0.3.3
transloadit 2.0.1

The error resulted from creating a new assembly and then calling `create!` on it.

**Comment by rmehner** [comment] 2020-10-28 17:27
@cspeer Does this happen erratically or all the time? If the latter, would you be able to have a reproducible example?

I have a hunch that it might be related on how the gem treats responses that don't look like it's expecting, but I'm not sure.

**Comment by cspeer** [comment] 2020-10-28 20:42
@rmehner It only happened once so far, but we are still in development. However, this is the first in at least 100 assemlies so far. So, I would have to see how much it actually happens once we start using it in production. I'm sorry that I don't really have much to go on here!

**Comment by rmehner** [comment] 2020-10-29 09:12
@cspeer Alright, please keep me posted so I can have a look. 

I suspect that we get an error back from transloadit without a JSON body and then this might happen, but I'm not entirely sure. The code in question https://github.com/transloadit/ruby-sdk/blob/master/lib/transloadit/request.rb#L168-L172

**Comment by cspeer** [comment] 2020-10-31 17:23
Yeah, I mean if it's not happening all the time, then it's probably just a timeout or some other kind of network issue which could easly be resolved by retrying 1-2 times.
Maybe, what you could do is fire up 1000 test connections to the API and see what other than a 200 HTTP status code comes back or if anything else like a timeout shows up.

I did something similar to avoid this problem. I put everything into a rails job which is then processed asyncronuously and if something goes wrong, the job will automatically try processing it again. Since then, I haven't had a problem.

**Comment by rmehner** [comment] 2020-11-01 10:43
Sounds like a reasonable way of dealing with services that go across a network connection any way.

I'll have a chat with Transloadit to see if I can force this error and maybe I can spend some time next weekend on improving the error at least (so it's clearer from the error message that something went wrong with the request. At least you should be able to see the http status)

**Comment by cspeer** [comment] 2020-11-01 15:04
That would be cool. Thanks :)

**Comment by juliangruber** [comment] 2021-04-14 10:26
1890 assemblies later, I haven't been able to reproduce with the example in this repo. I'll try mirroring the assembly instructions in https://github.com/transloadit/ruby-sdk/issues/53#issue-375807607 next.

**Comment by juliangruber** [comment] 2021-04-14 11:26
I'm having troubles getting ruby 1.9.3 to run on my system, can someone else try to reproduce this? 🤔

**Comment by rmehner** [comment] 2021-04-14 11:34
> I'm having troubles getting ruby 1.9.3 to run on my system, can someone else try to reproduce this? 🤔

My hunch is that this happens when you lose connection to Transloadit in between for whatever reason. @cspeer said he's using Ruby 2.7.2, so it's definitely not 1.9.3 playing a role there.

**Comment by thatandyrose** [comment] 2021-08-09 12:59
hi there, just want to say I get this issue sporadically with gem version 2.0.1.

To the maintainer... I don't think there's an issue with your gem itself. BUT, the fact that it just returns a nil response object might be the issue.

Ideally if a timeout or 4xx/5xx happens then it would be nicer if the gem raised that up to the caller so we can handle it? Having a nil response object is just a bit odd.

Just to clarify, this only happens sometimes, and of course it's impossible to know which assembly or even if the assembly was created since the response is nil

**Comment by Acconut** [comment] 2024-01-10 08:13
I am able to reproduce this problem by setting the endpoint to something like `http://1.2.3.4/`. We are not able to connect to this IP, so after some time (timeout plus retries), I get the same error message:

```
$ ruby main.rb
"starting image transcoding job..."
"fetching image from the cat api..."
"starting transcoding job..."
"s3 config not set. Skipping s3 storage..."
/Users/marius/workspace/transloadit/ruby-sdk/lib/transloadit/response.rb:34:in `body': undefined method `body' for nil:NilClass (NoMethodError)

    MultiJson.load __getobj__.body
                             ^^^^^
        from /Users/marius/workspace/transloadit/ruby-sdk/lib/transloadit/response.rb:25:in `[]'
        from /Users/marius/workspace/transloadit/ruby-sdk/lib/transloadit/response/assembly.rb:45:in `rate_limit?'
        from /Users/marius/workspace/transloadit/ruby-sdk/lib/transloadit/assembly.rb:63:in `block in create!'
        from /Users/marius/workspace/transloadit/ruby-sdk/lib/transloadit/assembly.rb:55:in `each'
        from /Users/marius/workspace/transloadit/ruby-sdk/lib/transloadit/assembly.rb:55:in `create!'
        from /Users/marius/workspace/transloadit/ruby-sdk/examples/basic/image-transcoder.rb:30:in `transcode!'
        from main.rb:16:in `block in <main>'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/open-uri.rb:157:in `open_uri'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/open-uri.rb:740:in `open'
        from /opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/open-uri.rb:29:in `open'
```

**Closed** 2024-01-10 11:36 UTC
Labels: sdks, prio-3
